# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: "https://sidetrend.com"
permalink: pretty
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page/:num"

# Collections
collections_dir: collections
collections:
  services:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

# Pages
defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: service
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: team
    values:
      layout: team
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Jekyll Advance"
category_dir: category

colors:
  #light-mode colors
  primary_bg: "#2b3af7"
  primary_bg_2: "#424ff8"
  primary_bg_3: "#702bf7"
  primary_text: "#fdfcf9"
  base_bg: "#ffffff"
  base_bg_2: "#f8f9ff"
  base_bg_3: "#eef2f9"
  text: "#0d042b"
  text_2: "#3b364c"
  logo_text: "#2b3af7"
  header_text: "#0d042b"

  # dark-mode colors
  primary_bg_dark: "#36BDE3"
  primary_bg_2_dark: "#101010"
  primary_bg_3_dark: "#702bf7"
  primary_text_dark: "#fdfcf9"
  base_bg_dark: "#101010"
  base_bg_2_dark: "#1C1C1E"
  base_bg_3_dark: "#2C2C2E"
  text_dark: "#FFFFFF"
  text_2_dark: "#8F8F96"
  logo_text_dark: "#36BDE3"
  header_text_dark: "#FFFFFF"

fonts:
  use_google_fonts: true
  google_fonts_url: "https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;700"
  use_self_hosted_fonts: false # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
  heading: "Figtree"
  base: "Figtree"
  monospace: "Figtree"
  logo: "Figtree"

logo:
  logo_text: "sidetrend"
  logo_image: assets/images/logo/logo.png
  logo_image_mobile: assets/images/logo/logo-mobile.png
  logo_image_invert: assets/images/logo/logo-invert.png
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
  logo_image_desktop_height: "34px"
  logo_image_desktop_width: "200px"
  logo_image_mobile_height: "30px"
  logo_image_mobile_width: "34px"
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: false

header: 
  fixed: false

open_graph:
  meta_opengraph_type: "website"
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: false
  show_dark_mode_toggle_in_bottom: true
  show_dark_mode_toggle_in_mobile_menu: false

cookie_banner:
  enabled: false
  show_manage_cookies_at_bottom: false

analytics:
  google_analytics_id: "" # G-XXXXXXXXXX
  gtm_id: "" # GTM-XXXXXXXX
  plausible_data_domain: "" # example: mywebsite.com
  umami_data_website_id: "" # example: "ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b"
  umami_src: "" # "https://analytics.eu.umami.is/script.js"

comments:
  commento:
    enabled: false # you must have a commento account and be on the correct domain. does not work locally.
  disqus:
    shortname: "" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.

newsletter:
  mailchimp:
    form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
    form_title: "Let's keep in touch"

contact_form: 
  use_netlify_form: true
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv
  netlify_form_name: "contact"

menu: 
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: false # show/hide the entire footer
  footer_title: "Sidetrend"
  footer_description: "Professional trading signals"
  enable_social_media_icons: false
  enable_contact_details: true
  enable_menu_footer_primary: false
  enable_menu_footer_secondary: false
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: "Product"
  footer_secondary_menu_title: "Company"
  footer_tertiary_menu_title: "Other"

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© NSWood, LLC t/a Sidetrend"
  show_rss_icon: false

sidebar:
  enable_sidebar_services: false
  enable_breadcrumbs_services: false
  enable_sidebar_projects: false
  enable_breadcrumbs_projects: false